export interface SeedWord {
  polish: string;
  russian: string;
}

export interface SeedCategory {
  name: string;
  words: SeedWord[];
}

/**
 * Стартовый системный словарь (ownerId = null).
 * В каждой категории минимум 10 слов и различные русские переводы
 * после нормализации — иначе категория не участвует в Тесте (§4.3).
 */
export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: 'Цвета',
    words: [
      { polish: 'czerwony', russian: 'красный' },
      { polish: 'niebieski', russian: 'синий' },
      { polish: 'zielony', russian: 'зелёный' },
      { polish: 'żółty', russian: 'жёлтый' },
      { polish: 'czarny', russian: 'чёрный' },
      { polish: 'biały', russian: 'белый' },
      { polish: 'szary', russian: 'серый' },
      { polish: 'brązowy', russian: 'коричневый' },
      { polish: 'różowy', russian: 'розовый' },
      { polish: 'pomarańczowy', russian: 'оранжевый' },
      { polish: 'fioletowy', russian: 'фиолетовый' },
      { polish: 'granatowy', russian: 'тёмно-синий' },
      { polish: 'złoty', russian: 'золотой' },
      { polish: 'srebrny', russian: 'серебряный' },
      { polish: 'jasny', russian: 'светлый' },
      { polish: 'ciemny', russian: 'тёмный' },
      { polish: 'kolorowy', russian: 'цветной' },
      { polish: 'przezroczysty', russian: 'прозрачный' },
      { polish: 'beżowy', russian: 'бежевый' },
    ],
  },
  {
    name: 'Еда',
    words: [
      { polish: 'chleb', russian: 'хлеб' },
      { polish: 'mleko', russian: 'молоко' },
      { polish: 'ser', russian: 'сыр' },
      { polish: 'masło', russian: 'сливочное масло' },
      { polish: 'jajko', russian: 'яйцо' },
      { polish: 'mięso', russian: 'мясо' },
      { polish: 'ryba', russian: 'рыба' },
      { polish: 'zupa', russian: 'суп' },
      { polish: 'woda', russian: 'вода' },
      { polish: 'herbata', russian: 'чай' },
      { polish: 'kawa', russian: 'кофе' },
      { polish: 'cukier', russian: 'сахар' },
      { polish: 'sól', russian: 'соль' },
      { polish: 'pieprz', russian: 'перец' },
      { polish: 'mąka', russian: 'мука' },
      { polish: 'olej', russian: 'масло растительное' },
      { polish: 'jabłko', russian: 'яблоко' },
      { polish: 'banan', russian: 'банан' },
      { polish: 'pomidor', russian: 'помидор' },
      { polish: 'ziemniak', russian: 'картофель' },
      { polish: 'marchewka', russian: 'морковь' },
      { polish: 'cebula', russian: 'лук' },
      { polish: 'ciasto', russian: 'пирог' },
      { polish: 'kanapka', russian: 'бутерброд' },
      { polish: 'śniadanie', russian: 'завтрак' },
      { polish: 'obiad', russian: 'обед' },
      { polish: 'kolacja', russian: 'ужин' },
      { polish: 'bułka', russian: 'булочка' },
      { polish: 'ryż', russian: 'рис' },
      { polish: 'makaron', russian: 'макароны' },
      { polish: 'płatki', russian: 'хлопья' },
      { polish: 'jogurt', russian: 'йогурт' },
      { polish: 'śmietana', russian: 'сметана' },
      { polish: 'twaróg', russian: 'творог' },
      { polish: 'dżem', russian: 'варенье' },
      { polish: 'miód', russian: 'мёд' },
      { polish: 'czekolada', russian: 'шоколад' },
      { polish: 'lody', russian: 'мороженое' },
      { polish: 'ciastko', russian: 'печенье' },
      { polish: 'pomarańcza', russian: 'апельсин' },
      { polish: 'cytryna', russian: 'лимон' },
      { polish: 'gruszka', russian: 'груша' },
      { polish: 'truskawka', russian: 'клубника' },
      { polish: 'winogrono', russian: 'виноград' },
      { polish: 'arbuz', russian: 'арбуз' },
      { polish: 'brzoskwinia', russian: 'персик' },
      { polish: 'wiśnia', russian: 'вишня' },
      { polish: 'ogórek', russian: 'огурец' },
      { polish: 'kapusta', russian: 'капуста' },
      { polish: 'sałata', russian: 'салат-латук' },
      { polish: 'papryka', russian: 'сладкий перец' },
      { polish: 'czosnek', russian: 'чеснок' },
      { polish: 'groszek', russian: 'горошек' },
      { polish: 'fasola', russian: 'фасоль' },
      { polish: 'kukurydza', russian: 'кукуруза' },
      { polish: 'kurczak', russian: 'курица, мясо' },
      { polish: 'wołowina', russian: 'говядина' },
      { polish: 'wieprzowina', russian: 'свинина' },
      { polish: 'kiełbasa', russian: 'колбаса' },
      { polish: 'szynka', russian: 'ветчина' },
      { polish: 'łosoś', russian: 'лосось' },
      { polish: 'sok', russian: 'сок' },
      { polish: 'napój', russian: 'напиток' },
      { polish: 'woda gazowana', russian: 'газированная вода' },
      { polish: 'woda niegazowana', russian: 'негазированная вода' },
      { polish: 'lemoniada', russian: 'лимонад' },
      { polish: 'piwo', russian: 'пиво' },
      { polish: 'wino', russian: 'вино' },
      { polish: 'danie', russian: 'блюдо' },
      { polish: 'sałatka', russian: 'салат' },
      { polish: 'sos', russian: 'соус' },
      { polish: 'deser', russian: 'десерт' },
    ],
  },
  {
    name: 'Семья',
    words: [
      { polish: 'mama', russian: 'мама' },
      { polish: 'tata', russian: 'папа' },
      { polish: 'siostra', russian: 'сестра' },
      { polish: 'brat', russian: 'брат' },
      { polish: 'babcia', russian: 'бабушка' },
      { polish: 'dziadek', russian: 'дедушка' },
      { polish: 'córka', russian: 'дочь' },
      { polish: 'syn', russian: 'сын' },
      { polish: 'żona', russian: 'жена' },
      { polish: 'mąż', russian: 'муж' },
      { polish: 'rodzina', russian: 'семья' },
      { polish: 'dziecko', russian: 'ребёнок' },
      { polish: 'rodzice', russian: 'родители' },
      { polish: 'dziadkowie', russian: 'бабушка и дедушка' },
      { polish: 'wujek', russian: 'дядя' },
      { polish: 'ciocia', russian: 'тётя' },
      { polish: 'kuzyn', russian: 'двоюродный брат' },
      { polish: 'kuzynka', russian: 'двоюродная сестра' },
      { polish: 'chłopak', russian: 'парень' },
      { polish: 'dziewczyna', russian: 'девушка' },
      { polish: 'przyjaciel', russian: 'друг' },
      { polish: 'przyjaciółka', russian: 'подруга' },
    ],
  },
  {
    name: 'Дом',
    words: [
      { polish: 'dom', russian: 'дом' },
      { polish: 'drzwi', russian: 'дверь' },
      { polish: 'okno', russian: 'окно' },
      { polish: 'stół', russian: 'стол' },
      { polish: 'krzesło', russian: 'стул' },
      { polish: 'łóżko', russian: 'кровать' },
      { polish: 'kuchnia', russian: 'кухня' },
      { polish: 'pokój', russian: 'комната' },
      { polish: 'lampa', russian: 'лампа' },
      { polish: 'klucz', russian: 'ключ' },
      { polish: 'łazienka', russian: 'ванная' },
      { polish: 'sypialnia', russian: 'спальня' },
      { polish: 'salon', russian: 'гостиная' },
      { polish: 'balkon', russian: 'балкон' },
      { polish: 'ściana', russian: 'стена' },
      { polish: 'podłoga', russian: 'пол' },
      { polish: 'sufit', russian: 'потолок' },
      { polish: 'szafa', russian: 'шкаф' },
      { polish: 'sofa', russian: 'диван' },
      { polish: 'fotel', russian: 'кресло' },
      { polish: 'lodówka', russian: 'холодильник' },
      { polish: 'piec', russian: 'плита' },
      { polish: 'talerz', russian: 'тарелка' },
      { polish: 'kubek', russian: 'кружка' },
      { polish: 'łyżka', russian: 'ложка' },
    ],
  },
  {
    name: 'Животные',
    words: [
      { polish: 'kot', russian: 'кот' },
      { polish: 'pies', russian: 'собака' },
      { polish: 'ptak', russian: 'птица' },
      { polish: 'koń', russian: 'лошадь' },
      { polish: 'krowa', russian: 'корова' },
      { polish: 'świnia', russian: 'свинья' },
      { polish: 'owca', russian: 'овца' },
      { polish: 'mysz', russian: 'мышь' },
      { polish: 'lis', russian: 'лиса' },
      { polish: 'wilk', russian: 'волк' },
      { polish: 'lew', russian: 'лев' },
      { polish: 'tygrys', russian: 'тигр' },
      { polish: 'słoń', russian: 'слон' },
      { polish: 'małpa', russian: 'обезьяна' },
      { polish: 'niedźwiedź', russian: 'медведь' },
      { polish: 'zając', russian: 'заяц' },
      { polish: 'jeleń', russian: 'олень' },
      { polish: 'żaba', russian: 'лягушка' },
      { polish: 'wąż', russian: 'змея' },
      { polish: 'motyl', russian: 'бабочка' },
      { polish: 'pszczółka', russian: 'пчела' },
      { polish: 'kaczka', russian: 'утка' },
      { polish: 'kura', russian: 'курица' },
      { polish: 'kogut', russian: 'петух' },
      { polish: 'królik', russian: 'кролик' },
    ],
  },
  {
    name: 'Приветствия и вежливость',
    words: [
      { polish: 'cześć', russian: 'привет' },
      { polish: 'dzień dobry', russian: 'добрый день' },
      { polish: 'dobry wieczór', russian: 'добрый вечер' },
      { polish: 'do widzenia', russian: 'до свидания' },
      { polish: 'do zobaczenia', russian: 'до встречи' },
      { polish: 'proszę', russian: 'пожалуйста' },
      { polish: 'dziękuję', russian: 'спасибо' },
      { polish: 'przepraszam', russian: 'извините' },
      { polish: 'tak', russian: 'да' },
      { polish: 'nie', russian: 'нет' },
      { polish: 'dobrze', russian: 'хорошо' },
      { polish: 'witaj', russian: 'здравствуй' },
      { polish: 'dzień dobry państwu', russian: 'добрый день всем' },
      { polish: 'dobranoc', russian: 'спокойной ночи' },
      { polish: 'miłego dnia', russian: 'хорошего дня' },
      { polish: 'powodzenia', russian: 'удачи' },
      { polish: 'smacznego', russian: 'приятного аппетита' },
      { polish: 'na zdrowie', russian: 'будь здоров' },
      { polish: 'oczywiście', russian: 'конечно' },
      { polish: 'może', russian: 'может быть' },
      { polish: 'razem', russian: 'вместе' },
      { polish: 'jeszcze', russian: 'ещё' },
      { polish: 'bardzo', russian: 'очень' },
      { polish: 'trochę', russian: 'немного' },
      { polish: 'naprawdę', russian: 'правда' },
    ],
  },
  {
    name: 'Числа',
    words: [
      { polish: 'jeden', russian: 'один' },
      { polish: 'dwa', russian: 'два' },
      { polish: 'trzy', russian: 'три' },
      { polish: 'cztery', russian: 'четыре' },
      { polish: 'pięć', russian: 'пять' },
      { polish: 'sześć', russian: 'шесть' },
      { polish: 'siedem', russian: 'семь' },
      { polish: 'osiem', russian: 'восемь' },
      { polish: 'dziewięć', russian: 'девять' },
      { polish: 'dziesięć', russian: 'десять' },
      { polish: 'sto', russian: 'сто' },
      { polish: 'tysiąc', russian: 'тысяча' },
      { polish: 'jedenaście', russian: 'одиннадцать' },
      { polish: 'dwanaście', russian: 'двенадцать' },
      { polish: 'trzynaście', russian: 'тринадцать' },
      { polish: 'czternaście', russian: 'четырнадцать' },
      { polish: 'piętnaście', russian: 'пятнадцать' },
      { polish: 'dwadzieścia', russian: 'двадцать' },
      { polish: 'trzydzieści', russian: 'тридцать' },
      { polish: 'czterdzieści', russian: 'сорок' },
      { polish: 'pięćdziesiąt', russian: 'пятьдесят' },
      { polish: 'milion', russian: 'миллион' },
      { polish: 'pierwszy', russian: 'первый' },
      { polish: 'drugi', russian: 'второй' },
      { polish: 'trzeci', russian: 'третий' },
    ],
  },
  {
    name: 'Календарь',
    words: [
      { polish: 'poniedziałek', russian: 'понедельник' },
      { polish: 'wtorek', russian: 'вторник' },
      { polish: 'środa', russian: 'среда' },
      { polish: 'czwartek', russian: 'четверг' },
      { polish: 'piątek', russian: 'пятница' },
      { polish: 'sobota', russian: 'суббота' },
      { polish: 'niedziela', russian: 'воскресенье' },
      { polish: 'styczeń', russian: 'январь' },
      { polish: 'luty', russian: 'февраль' },
      { polish: 'marzec', russian: 'март' },
      { polish: 'kwiecień', russian: 'апрель' },
      { polish: 'maj', russian: 'май' },
      { polish: 'czerwiec', russian: 'июнь' },
      { polish: 'lipiec', russian: 'июль' },
      { polish: 'sierpień', russian: 'август' },
      { polish: 'wrzesień', russian: 'сентябрь' },
      { polish: 'październik', russian: 'октябрь' },
      { polish: 'listopad', russian: 'ноябрь' },
      { polish: 'grudzień', russian: 'декабрь' },
      { polish: 'tydzień', russian: 'неделя' },
      { polish: 'miesiąc', russian: 'месяц' },
      { polish: 'rok', russian: 'год' },
      { polish: 'weekend', russian: 'выходные' },
      { polish: 'urodziny', russian: 'день рождения' },
    ],
  },
  {
    name: 'Время',
    words: [
      { polish: 'czas', russian: 'время' },
      { polish: 'godzina', russian: 'час' },
      { polish: 'minuta', russian: 'минута' },
      { polish: 'sekunda', russian: 'секунда' },
      { polish: 'rano', russian: 'утром' },
      { polish: 'południe', russian: 'полдень' },
      { polish: 'popołudnie', russian: 'день после полудня' },
      { polish: 'wieczór', russian: 'вечер' },
      { polish: 'noc', russian: 'ночь' },
      { polish: 'dzisiaj', russian: 'сегодня' },
      { polish: 'jutro', russian: 'завтра' },
      { polish: 'wczoraj', russian: 'вчера' },
      { polish: 'teraz', russian: 'сейчас' },
      { polish: 'później', russian: 'позже' },
      { polish: 'wcześnie', russian: 'рано' },
      { polish: 'późno', russian: 'поздно' },
      { polish: 'zawsze', russian: 'всегда' },
      { polish: 'nigdy', russian: 'никогда' },
      { polish: 'często', russian: 'часто' },
      { polish: 'czasami', russian: 'иногда' },
      { polish: 'godzina pierwsza', russian: 'час дня' },
      { polish: 'pół godziny', russian: 'полчаса' },
      { polish: 'kwadrans', russian: 'четверть часа' },
      { polish: 'moment', russian: 'мгновение' },
    ],
  },
  {
    name: 'Погода',
    words: [
      { polish: 'pogoda', russian: 'погода' },
      { polish: 'słońce', russian: 'солнце' },
      { polish: 'deszcz', russian: 'дождь' },
      { polish: 'śnieg', russian: 'снег' },
      { polish: 'wiatr', russian: 'ветер' },
      { polish: 'chmura', russian: 'облако' },
      { polish: 'mgła', russian: 'туман' },
      { polish: 'burza', russian: 'гроза' },
      { polish: 'ciepło', russian: 'тепло' },
      { polish: 'zimno', russian: 'холодно' },
      { polish: 'gorąco', russian: 'жарко' },
      { polish: 'mokro', russian: 'мокро' },
      { polish: 'cień', russian: 'тень' },
      { polish: 'temperatura', russian: 'температура' },
      { polish: 'stopień', russian: 'градус' },
      { polish: 'lód', russian: 'лёд' },
      { polish: 'kropla', russian: 'капля' },
      { polish: 'tęcza', russian: 'радуга' },
      { polish: 'błyskawica', russian: 'молния' },
      { polish: 'grzmot', russian: 'гром' },
      { polish: 'mroźny', russian: 'морозный' },
      { polish: 'wietrzny', russian: 'ветреный' },
      { polish: 'słoneczny', russian: 'солнечный' },
      { polish: 'pochmurny', russian: 'пасмурный' },
    ],
  },
  {
    name: 'Одежда',
    words: [
      { polish: 'koszula', russian: 'рубашка' },
      { polish: 'bluzka', russian: 'блузка' },
      { polish: 'spodnie', russian: 'брюки' },
      { polish: 'sukienka', russian: 'платье' },
      { polish: 'spódnica', russian: 'юбка' },
      { polish: 'kurtka', russian: 'куртка' },
      { polish: 'płaszcz', russian: 'пальто' },
      { polish: 'sweter', russian: 'свитер' },
      { polish: 'buty', russian: 'обувь' },
      { polish: 'skarpetka', russian: 'носок' },
      { polish: 'czapka', russian: 'шапка' },
      { polish: 'szalik', russian: 'шарф' },
      { polish: 'pasek', russian: 'ремень' },
      { polish: 'krawat', russian: 'галстук' },
      { polish: 'rękawiczki', russian: 'перчатки' },
      { polish: 'piżama', russian: 'пижама' },
      { polish: 'majtki', russian: 'трусы' },
      { polish: 'biustonosz', russian: 'бюстгальтер' },
      { polish: 'kieszeń', russian: 'карман' },
      { polish: 'guzik', russian: 'пуговица' },
      { polish: 'zamek', russian: 'молния на одежде' },
      { polish: 'rozmiar', russian: 'размер' },
      { polish: 'modny', russian: 'модный' },
      { polish: 'wygodny', russian: 'удобный' },
      { polish: 'czysty', russian: 'чистый' },
    ],
  },
  {
    name: 'Тело',
    words: [
      { polish: 'głowa', russian: 'голова' },
      { polish: 'włosy', russian: 'волосы' },
      { polish: 'oko', russian: 'глаз' },
      { polish: 'ucho', russian: 'ухо' },
      { polish: 'nos', russian: 'нос' },
      { polish: 'usta', russian: 'рот' },
      { polish: 'ząb', russian: 'зуб' },
      { polish: 'szyja', russian: 'шея' },
      { polish: 'ręka', russian: 'рука' },
      { polish: 'palec', russian: 'палец' },
      { polish: 'noga', russian: 'нога' },
      { polish: 'serce', russian: 'сердце' },
      { polish: 'twarz', russian: 'лицо' },
      { polish: 'czoło', russian: 'лоб' },
      { polish: 'policzek', russian: 'щека' },
      { polish: 'broda', russian: 'подбородок' },
      { polish: 'ramię', russian: 'плечо' },
      { polish: 'łokieć', russian: 'локоть' },
      { polish: 'dłoń', russian: 'ладонь' },
      { polish: 'brzuch', russian: 'живот' },
      { polish: 'plecy', russian: 'спина' },
      { polish: 'kolano', russian: 'колено' },
      { polish: 'stopa', russian: 'стопа' },
      { polish: 'skóra', russian: 'кожа' },
      { polish: 'krew', russian: 'кровь' },
    ],
  },
  {
    name: 'Учёба',
    words: [
      { polish: 'szkoła', russian: 'школа' },
      { polish: 'klasa', russian: 'класс' },
      { polish: 'lekcja', russian: 'урок' },
      { polish: 'nauczyciel', russian: 'учитель' },
      { polish: 'uczeń', russian: 'ученик' },
      { polish: 'książka', russian: 'книга' },
      { polish: 'zeszyt', russian: 'тетрадь' },
      { polish: 'długopis', russian: 'ручка' },
      { polish: 'ołówek', russian: 'карандаш' },
      { polish: 'gumka', russian: 'ластик' },
      { polish: 'pytanie', russian: 'вопрос' },
      { polish: 'odpowiedź', russian: 'ответ' },
      { polish: 'student', russian: 'студент' },
      { polish: 'studentka', russian: 'студентка' },
      { polish: 'uniwersytet', russian: 'университет' },
      { polish: 'przerwa', russian: 'перемена' },
      { polish: 'egzamin', russian: 'экзамен' },
      { polish: 'zadanie', russian: 'задание' },
      { polish: 'ćwiczenie', russian: 'упражнение' },
      { polish: 'słowo', russian: 'слово' },
      { polish: 'zdanie', russian: 'предложение' },
      { polish: 'język', russian: 'язык' },
      { polish: 'polski', russian: 'польский язык' },
      { polish: 'znaczenie', russian: 'значение' },
      { polish: 'błąd', russian: 'ошибка' },
    ],
  },
  {
    name: 'Транспорт',
    words: [
      { polish: 'samochód', russian: 'автомобиль' },
      { polish: 'autobus', russian: 'автобус' },
      { polish: 'tramwaj', russian: 'трамвай' },
      { polish: 'pociąg', russian: 'поезд' },
      { polish: 'rower', russian: 'велосипед' },
      { polish: 'samolot', russian: 'самолёт' },
      { polish: 'statek', russian: 'корабль' },
      { polish: 'taksówka', russian: 'такси' },
      { polish: 'bilet', russian: 'билет' },
      { polish: 'przystanek', russian: 'остановка' },
      { polish: 'dworzec', russian: 'вокзал' },
      { polish: 'lotnisko', russian: 'аэропорт' },
      { polish: 'metro', russian: 'метро' },
      { polish: 'motocykl', russian: 'мотоцикл' },
      { polish: 'hulajnoga', russian: 'самокат' },
      { polish: 'stateczek', russian: 'катер' },
      { polish: 'kierowca', russian: 'водитель' },
      { polish: 'pasażer', russian: 'пассажир' },
      { polish: 'droga', russian: 'дорога' },
      { polish: 'most', russian: 'мост' },
      { polish: 'skrzyżowanie', russian: 'перекрёсток' },
      { polish: 'światła', russian: 'светофор' },
      { polish: 'lewo', russian: 'лево' },
      { polish: 'prawo', russian: 'право' },
      { polish: 'prosto', russian: 'прямо' },
    ],
  },
  {
    name: 'Город',
    words: [
      { polish: 'miasto', russian: 'город' },
      { polish: 'ulica', russian: 'улица' },
      { polish: 'plac', russian: 'площадь' },
      { polish: 'park', russian: 'парк' },
      { polish: 'sklep', russian: 'магазин' },
      { polish: 'apteka', russian: 'аптека' },
      { polish: 'szpital', russian: 'больница' },
      { polish: 'bank', russian: 'банк' },
      { polish: 'poczta', russian: 'почта' },
      { polish: 'restauracja', russian: 'ресторан' },
      { polish: 'kawiarnia', russian: 'кафе' },
      { polish: 'muzeum', russian: 'музей' },
      { polish: 'kino', russian: 'кинотеатр' },
      { polish: 'teatr', russian: 'театр' },
      { polish: 'biblioteka', russian: 'библиотека' },
      { polish: 'kościół', russian: 'церковь' },
      { polish: 'hotel', russian: 'отель' },
      { polish: 'rynek', russian: 'рыночная площадь' },
      { polish: 'budynek', russian: 'здание' },
      { polish: 'adres', russian: 'адрес' },
      { polish: 'numer', russian: 'номер' },
      { polish: 'centrum', russian: 'центр' },
      { polish: 'dzielnica', russian: 'район' },
      { polish: 'wieś', russian: 'деревня' },
    ],
  },
  {
    name: 'Природа',
    words: [
      { polish: 'drzewo', russian: 'дерево' },
      { polish: 'kwiat', russian: 'цветок' },
      { polish: 'trawa', russian: 'трава' },
      { polish: 'las', russian: 'лес' },
      { polish: 'góra', russian: 'гора' },
      { polish: 'rzeka', russian: 'река' },
      { polish: 'jezioro', russian: 'озеро' },
      { polish: 'morze', russian: 'море' },
      { polish: 'plaża', russian: 'пляж' },
      { polish: 'ziemia', russian: 'земля' },
      { polish: 'kamień', russian: 'камень' },
      { polish: 'niebo', russian: 'небо' },
      { polish: 'powietrze', russian: 'воздух' },
      { polish: 'księżyc', russian: 'луна' },
      { polish: 'gwiazda', russian: 'звезда' },
      { polish: 'ogień', russian: 'огонь' },
      { polish: 'pole', russian: 'поле' },
      { polish: 'ogród', russian: 'сад' },
      { polish: 'wyspa', russian: 'остров' },
      { polish: 'dolina', russian: 'долина' },
      { polish: 'jaskinia', russian: 'пещера' },
      { polish: 'liść', russian: 'лист' },
      { polish: 'gałąź', russian: 'ветка' },
      { polish: 'grzyb', russian: 'гриб' },
    ],
  },
  {
    name: 'Повседневные глаголы',
    words: [
      { polish: 'być', russian: 'быть' },
      { polish: 'mieć', russian: 'иметь' },
      { polish: 'robić', russian: 'делать' },
      { polish: 'iść', russian: 'идти' },
      { polish: 'jechać', russian: 'ехать' },
      { polish: 'mówić', russian: 'говорить' },
      { polish: 'słuchać', russian: 'слушать' },
      { polish: 'czytać', russian: 'читать' },
      { polish: 'pisać', russian: 'писать' },
      { polish: 'jeść', russian: 'есть' },
      { polish: 'pić', russian: 'пить' },
      { polish: 'spać', russian: 'спать' },
      { polish: 'wstawać', russian: 'вставать' },
      { polish: 'siedzieć', russian: 'сидеть' },
      { polish: 'stać', russian: 'стоять' },
      { polish: 'patrzeć', russian: 'смотреть' },
      { polish: 'widzieć', russian: 'видеть' },
      { polish: 'znać', russian: 'знать' },
      { polish: 'rozumieć', russian: 'понимать' },
      { polish: 'lubić', russian: 'любить / нравиться' },
      { polish: 'chcieć', russian: 'хотеть' },
      { polish: 'móc', russian: 'мочь' },
      { polish: 'musieć', russian: 'быть должным' },
      { polish: 'kupować', russian: 'покупать' },
      { polish: 'sprzedawać', russian: 'продавать' },
      { polish: 'otwierać', russian: 'открывать' },
      { polish: 'zamykać', russian: 'закрывать' },
    ],
  },
  {
    name: 'Чувства и состояния',
    words: [
      { polish: 'szczęśliwy', russian: 'счастливый' },
      { polish: 'smutny', russian: 'грустный' },
      { polish: 'zmęczony', russian: 'уставший' },
      { polish: 'głodny', russian: 'голодный' },
      { polish: 'spragniony', russian: 'испытывающий жажду' },
      { polish: 'chory', russian: 'больной' },
      { polish: 'zdrowy', russian: 'здоровый' },
      { polish: 'spokojny', russian: 'спокойный' },
      { polish: 'zły', russian: 'злой' },
      { polish: 'wesoły', russian: 'весёлый' },
      { polish: 'ważny', russian: 'важный' },
      { polish: 'gotowy', russian: 'готовый' },
      { polish: 'zadowolony', russian: 'довольный' },
      { polish: 'zdenerwowany', russian: 'взволнованный' },
      { polish: 'przestraszony', russian: 'испуганный' },
      { polish: 'zajęty', russian: 'занятый' },
      { polish: 'wolny', russian: 'свободный' },
      { polish: 'pewny', russian: 'уверенный' },
      { polish: 'niepewny', russian: 'неуверенный' },
      { polish: 'ciekawy', russian: 'любопытный' },
      { polish: 'znudzony', russian: 'скучающий' },
      { polish: 'chętny', russian: 'желающий' },
      { polish: 'smaczny', russian: 'вкусный' },
      { polish: 'łatwy', russian: 'лёгкий' },
      { polish: 'trudny', russian: 'трудный' },
    ],
  },
  {
    name: 'Вопросительные слова',
    words: [
      { polish: 'kto', russian: 'кто' },
      { polish: 'co', russian: 'что' },
      { polish: 'gdzie', russian: 'где' },
      { polish: 'dokąd', russian: 'куда' },
      { polish: 'skąd', russian: 'откуда' },
      { polish: 'kiedy', russian: 'когда' },
      { polish: 'dlaczego', russian: 'почему' },
      { polish: 'jak', russian: 'как' },
      { polish: 'jaki', russian: 'какой' },
      { polish: 'czyj', russian: 'чей' },
      { polish: 'ile', russian: 'сколько' },
      { polish: 'który', russian: 'который' },
      { polish: 'czy', russian: 'ли' },
      { polish: 'ile razy', russian: 'сколько раз' },
      { polish: 'jak długo', russian: 'как долго' },
      { polish: 'jak często', russian: 'как часто' },
      { polish: 'z kim', russian: 'с кем' },
      { polish: 'dla kogo', russian: 'для кого' },
      { polish: 'od kiedy', russian: 'с каких пор' },
      { polish: 'do kiedy', russian: 'до каких пор' },
      { polish: 'po co', russian: 'зачем' },
      { polish: 'co to', russian: 'что это' },
    ],
  },
  {
    name: 'Хобби',
    words: [
      { polish: 'muzyka', russian: 'музыка' },
      { polish: 'film', russian: 'фильм' },
      { polish: 'teatr', russian: 'театр' },
      { polish: 'sport', russian: 'спорт' },
      { polish: 'piłka', russian: 'мяч' },
      { polish: 'taniec', russian: 'танец' },
      { polish: 'śpiewać', russian: 'петь' },
      { polish: 'rysowanie', russian: 'рисование' },
      { polish: 'gotowanie', russian: 'готовка' },
      { polish: 'podróż', russian: 'путешествие' },
      { polish: 'fotografia', russian: 'фотография' },
      { polish: 'gra', russian: 'игра' },
      { polish: 'czytanie', russian: 'чтение' },
      { polish: 'książka', russian: 'книга' },
      { polish: 'spacer', russian: 'прогулка' },
      { polish: 'pływanie', russian: 'плавание' },
      { polish: 'bieganie', russian: 'бег' },
      { polish: 'jazda', russian: 'езда' },
      { polish: 'wędrowanie', russian: 'походы' },
      { polish: 'ogród', russian: 'садоводство' },
      { polish: 'kolekcja', russian: 'коллекция' },
      { polish: 'instrument', russian: 'инструмент' },
      { polish: 'gitara', russian: 'гитара' },
      { polish: 'fotografować', russian: 'фотографировать' },
      { polish: 'malować', russian: 'рисовать красками' },
    ],
  },
  {
    name: 'Личные местоимения',
    words: [
      { polish: 'ja', russian: 'я' },
      { polish: 'ty', russian: 'ты' },
      { polish: 'on', russian: 'он' },
      { polish: 'ona', russian: 'она' },
      { polish: 'ono', russian: 'оно' },
      { polish: 'my', russian: 'мы' },
      { polish: 'wy', russian: 'вы' },
      { polish: 'oni', russian: 'они, мин 1 мужчина' },
      { polish: 'one', russian: 'они, женщины' },
      { polish: 'mnie', russian: 'меня' },
      { polish: 'ciebie', russian: 'тебя' },
      { polish: 'jego', russian: 'его' },
      { polish: 'jej', russian: 'её' },
      { polish: 'nas', russian: 'нас' },
      { polish: 'was', russian: 'вас' },
      { polish: 'ktoś', russian: 'кто-то' },
      { polish: 'nikt', russian: 'никто' },
    ],
  },
  {
    name: 'Базовые прилагательные',
    words: [
      { polish: 'dobry', russian: 'хороший' },
      { polish: 'zły', russian: 'плохой' },
      { polish: 'duży', russian: 'большой' },
      { polish: 'mały', russian: 'маленький' },
      { polish: 'nowy', russian: 'новый' },
      { polish: 'stary', russian: 'старый' },
      { polish: 'młody', russian: 'молодой' },
      { polish: 'piękny', russian: 'красивый' },
      { polish: 'brzydki', russian: 'некрасивый' },
      { polish: 'dużo', russian: 'много' },
      { polish: 'mało', russian: 'мало' },
      { polish: 'długi', russian: 'длинный' },
      { polish: 'krótki', russian: 'короткий' },
      { polish: 'wysoki', russian: 'высокий' },
      { polish: 'niski', russian: 'низкий' },
      { polish: 'szybki', russian: 'быстрый' },
      { polish: 'wolny', russian: 'медленный' },
      { polish: 'silny', russian: 'сильный' },
      { polish: 'słaby', russian: 'слабый' },
      { polish: 'drogi', russian: 'дорогой' },
      { polish: 'tani', russian: 'дешёвый' },
      { polish: 'łatwy', russian: 'лёгкий' },
      { polish: 'trudny', russian: 'трудный' },
      { polish: 'czysty', russian: 'чистый' },
      { polish: 'brudny', russian: 'грязный' },
    ],
  },
  {
    name: 'Союзы и связки',
    words: [
      { polish: 'i', russian: 'и' },
      { polish: 'ale', russian: 'но' },
      { polish: 'bo', russian: 'потому что' },
      { polish: 'że', russian: 'что' },
      { polish: 'albo', russian: 'или' },
      { polish: 'lub', russian: 'либо' },
      { polish: 'więc', russian: 'поэтому' },
      { polish: 'dlatego', russian: 'по этой причине' },
      { polish: 'też', russian: 'тоже' },
      { polish: 'także', russian: 'также' },
      { polish: 'tylko', russian: 'только' },
      { polish: 'jeszcze', russian: 'ещё' },
      { polish: 'już', russian: 'уже' },
      { polish: 'bardzo', russian: 'очень' },
      { polish: 'trochę', russian: 'немного' },
      { polish: 'razem', russian: 'вместе' },
      { polish: 'może', russian: 'может быть' },
    ],
  },
  {
    name: 'Покупки и деньги',
    words: [
      { polish: 'pieniądze', russian: 'деньги' },
      { polish: 'cena', russian: 'цена' },
      { polish: 'koszt', russian: 'стоимость' },
      { polish: 'złoty', russian: 'злотый' },
      { polish: 'grosz', russian: 'грош' },
      { polish: 'gotówka', russian: 'наличные' },
      { polish: 'karta', russian: 'карта' },
      { polish: 'portfel', russian: 'кошелёк' },
      { polish: 'paragon', russian: 'чек из магазина' },
      { polish: 'rachunek', russian: 'счёт к оплате' },
      { polish: 'sklep', russian: 'магазин' },
      { polish: 'supermarket', russian: 'супермаркет' },
      { polish: 'targ', russian: 'рынок' },
      { polish: 'towar', russian: 'товар' },
      { polish: 'produkt', russian: 'продукт' },
      { polish: 'koszyk', russian: 'корзина' },
      { polish: 'torba', russian: 'сумка' },
      { polish: 'rozmiar', russian: 'размер' },
      { polish: 'przymierzalnia', russian: 'примерочная' },
      { polish: 'rabat', russian: 'скидка' },
      { polish: 'promocja', russian: 'акция' },
      { polish: 'paragon fiskalny', russian: 'кассовый чек' },
    ],
  },
  {
    name: 'Кафе и ресторан',
    words: [
      { polish: 'menu', russian: 'меню' },
      { polish: 'kelner', russian: 'официант' },
      { polish: 'kelnerka', russian: 'официантка' },
      { polish: 'gość', russian: 'гость' },
      { polish: 'stolik', russian: 'столик' },
      { polish: 'śniadanie', russian: 'завтрак' },
      { polish: 'lunch', russian: 'ланч' },
      { polish: 'deser', russian: 'десерт' },
      { polish: 'danie', russian: 'блюдо' },
      { polish: 'porcja', russian: 'порция' },
      { polish: 'sos', russian: 'соус' },
      { polish: 'widelec', russian: 'вилка' },
      { polish: 'nóż', russian: 'нож' },
      { polish: 'serwetka', russian: 'салфетка' },
      { polish: 'szklanka', russian: 'стакан' },
      { polish: 'filiżanka', russian: 'чашка' },
      { polish: 'rachunek', russian: 'счёт' },
      { polish: 'rezerwacja', russian: 'бронирование' },
      { polish: 'wegetariański', russian: 'вегетарианский' },
      { polish: 'ostry', russian: 'острый' },
    ],
  },
  {
    name: 'Здоровье и врач',
    words: [
      { polish: 'lekarz', russian: 'врач' },
      { polish: 'lekarka', russian: 'врач-женщина' },
      { polish: 'pacjent', russian: 'пациент' },
      { polish: 'choroba', russian: 'болезнь' },
      { polish: 'ból', russian: 'боль' },
      { polish: 'gorączka', russian: 'температура, жар' },
      { polish: 'kaszel', russian: 'кашель' },
      { polish: 'katar', russian: 'насморк' },
      { polish: 'ból głowy', russian: 'головная боль' },
      { polish: 'rana', russian: 'рана' },
      { polish: 'apteka', russian: 'аптека' },
      { polish: 'lekarstwo', russian: 'лекарство' },
      { polish: 'tabletka', russian: 'таблетка' },
      { polish: 'recepta', russian: 'рецепт врача' },
      { polish: 'szpital', russian: 'больница' },
      { polish: 'dentysta', russian: 'стоматолог' },
      { polish: 'pielęgniarka', russian: 'медсестра' },
      { polish: 'wizyta', russian: 'приём, визит' },
      { polish: 'oddychać', russian: 'дышать' },
      { polish: 'odpoczywać', russian: 'отдыхать' },
      { polish: 'zdrowie', russian: 'здоровье' },
    ],
  },
  {
    name: 'Работа и профессии',
    words: [
      { polish: 'praca', russian: 'работа' },
      { polish: 'pracownik', russian: 'работник' },
      { polish: 'szef', russian: 'начальник' },
      { polish: 'kolega', russian: 'коллега-мужчина' },
      { polish: 'koleżanka', russian: 'коллега-женщина' },
      { polish: 'biuro', russian: 'офис' },
      { polish: 'firma', russian: 'компания' },
      { polish: 'spotkanie', russian: 'встреча' },
      { polish: 'telefon', russian: 'телефон' },
      { polish: 'komputer', russian: 'компьютер' },
      { polish: 'pensja', russian: 'зарплата' },
      { polish: 'urlop', russian: 'отпуск' },
      { polish: 'zawód', russian: 'профессия' },
      { polish: 'policjant', russian: 'полицейский' },
      { polish: 'strażak', russian: 'пожарный' },
      { polish: 'kierowca', russian: 'водитель' },
      { polish: 'sprzedawca', russian: 'продавец' },
      { polish: 'kucharz', russian: 'повар' },
      { polish: 'inżynier', russian: 'инженер' },
      { polish: 'artysta', russian: 'художник, артист' },
      { polish: 'bezrobotny', russian: 'безработный' },
    ],
  },
  {
    name: 'Распорядок дня',
    words: [
      { polish: 'budzić się', russian: 'просыпаться' },
      { polish: 'wstawać', russian: 'вставать' },
      { polish: 'myć się', russian: 'мыться' },
      { polish: 'ubierać się', russian: 'одеваться' },
      { polish: 'czesać się', russian: 'причёсываться' },
      { polish: 'jeść śniadanie', russian: 'завтракать' },
      { polish: 'iść do pracy', russian: 'идти на работу' },
      { polish: 'wracać', russian: 'возвращаться' },
      { polish: 'robić zakupy', russian: 'делать покупки' },
      { polish: 'sprzątać', russian: 'убираться' },
      { polish: 'gotować', russian: 'готовить' },
      { polish: 'oglądać telewizję', russian: 'смотреть телевизор' },
      { polish: 'dzwonić', russian: 'звонить' },
      { polish: 'spotykać się', russian: 'встречаться' },
      { polish: 'uczyć się', russian: 'учиться' },
      { polish: 'ćwiczyć', russian: 'тренироваться' },
      { polish: 'brać prysznic', russian: 'принимать душ' },
      { polish: 'kłaść się spać', russian: 'ложиться спать' },
      { polish: 'zasypiać', russian: 'засыпать' },
    ],
  },
  {
    name: 'Общение',
    words: [
      { polish: 'rozmowa', russian: 'разговор' },
      { polish: 'wiadomość', russian: 'сообщение' },
      { polish: 'telefonować', russian: 'звонить по телефону' },
      { polish: 'pisać wiadomość', russian: 'писать сообщение' },
      { polish: 'mówić wolniej', russian: 'говорить медленнее' },
      { polish: 'powtórzyć', russian: 'повторить' },
      { polish: 'rozumieć', russian: 'понимать' },
      { polish: 'nie rozumieć', russian: 'не понимать' },
      { polish: 'znać', russian: 'знать' },
      { polish: 'przedstawić się', russian: 'представиться' },
      { polish: 'nazywać się', russian: 'называться' },
      { polish: 'pytać', russian: 'спрашивать' },
      { polish: 'odpowiadać', russian: 'отвечать' },
      { polish: 'wyjaśniać', russian: 'объяснять' },
      { polish: 'tłumaczyć', russian: 'переводить, объяснять' },
      { polish: 'pomagać', russian: 'помогать' },
      { polish: 'słownik', russian: 'словарь' },
      { polish: 'znak', russian: 'знак' },
      { polish: 'głos', russian: 'голос' },
    ],
  },
  {
    name: 'Путешествия и гостиница',
    words: [
      { polish: 'podróż', russian: 'путешествие' },
      { polish: 'wycieczka', russian: 'экскурсия' },
      { polish: 'wakacje', russian: 'каникулы, отпуск' },
      { polish: 'hotel', russian: 'отель' },
      { polish: 'pokój hotelowy', russian: 'номер в отеле' },
      { polish: 'recepcja', russian: 'ресепшен' },
      { polish: 'klucz', russian: 'ключ' },
      { polish: 'rezerwacja', russian: 'бронирование' },
      { polish: 'paszport', russian: 'паспорт' },
      { polish: 'dokument', russian: 'документ' },
      { polish: 'walizka', russian: 'чемодан' },
      { polish: 'plecak', russian: 'рюкзак' },
      { polish: 'bagaż', russian: 'багаж' },
      { polish: 'mapa', russian: 'карта' },
      { polish: 'granica', russian: 'граница' },
      { polish: 'zagranica', russian: 'заграница' },
      { polish: 'plaża', russian: 'пляж' },
      { polish: 'zwiedzać', russian: 'осматривать достопримечательности' },
      { polish: 'wynajmować', russian: 'арендовать' },
      { polish: 'nocleg', russian: 'ночлег' },
      { polish: 'wolny pokój', russian: 'свободный номер' },
    ],
  },
  {
    name: 'Направления и расположение',
    words: [
      { polish: 'lewo', russian: 'лево' },
      { polish: 'prawo', russian: 'право' },
      { polish: 'prosto', russian: 'прямо' },
      { polish: 'tutaj', russian: 'здесь' },
      { polish: 'tam', russian: 'там' },
      { polish: 'blisko', russian: 'близко' },
      { polish: 'daleko', russian: 'далеко' },
      { polish: 'naprzeciwko', russian: 'напротив' },
      { polish: 'obok', russian: 'рядом' },
      { polish: 'wewnątrz', russian: 'внутри' },
      { polish: 'na zewnątrz', russian: 'снаружи' },
      { polish: 'góra', russian: 'верх' },
      { polish: 'dół', russian: 'низ' },
      { polish: 'przód', russian: 'передняя часть' },
      { polish: 'tył', russian: 'задняя часть' },
      { polish: 'róg', russian: 'угол' },
      { polish: 'koniec', russian: 'конец' },
      { polish: 'początek', russian: 'начало' },
      { polish: 'adres', russian: 'адрес' },
      { polish: 'znaleźć', russian: 'найти' },
      { polish: 'zgubić się', russian: 'заблудиться' },
    ],
  },
  {
    name: 'Технологии и интернет',
    words: [
      { polish: 'komputer', russian: 'компьютер' },
      { polish: 'telefon komórkowy', russian: 'мобильный телефон' },
      { polish: 'laptop', russian: 'ноутбук' },
      { polish: 'ekran', russian: 'экран' },
      { polish: 'klawiatura', russian: 'клавиатура' },
      { polish: 'mysz komputerowa', russian: 'компьютерная мышь' },
      { polish: 'ładowarka', russian: 'зарядка' },
      { polish: 'bateria', russian: 'батарея' },
      { polish: 'internet', russian: 'интернет' },
      { polish: 'strona', russian: 'страница, сайт' },
      { polish: 'aplikacja', russian: 'приложение' },
      { polish: 'hasło', russian: 'пароль' },
      { polish: 'konto', russian: 'аккаунт, счёт' },
      { polish: 'e-mail', russian: 'электронная почта' },
      { polish: 'zdjęcie', russian: 'фотография' },
      { polish: 'plik', russian: 'файл' },
      { polish: 'pobierać', russian: 'скачивать' },
      { polish: 'wysyłać', russian: 'отправлять' },
      { polish: 'drukować', russian: 'печатать' },
    ],
  },
];
